# Generated by Django 4.0.1 on 2022-02-01 00:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('accountId', models.UUIDField(default=uuid.uuid4)),
                ('firstName', models.TextField(max_length=100)),
                ('lastName', models.TextField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('phone', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('core.basemodel',),
        ),
    ]
